[package]
name = "counter_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "counter_lib"
crate-type = ["cdylib"]

[dependencies]
arm = { path = "../aarm-risc0/arm", features = ["nif"] }
risc0-zkvm = { version = "2.0.2", features = ["prove", "std", "unstable"] }
#serde = { version = "1.0.197", default-features = false }
#serde_json = "1.0"
#tracing-subscriber = { version = "0.3", features = ["env-filter"] }
#k256 = { version = "=0.13.3", features = ["arithmetic", "serde", "expose-field", "std", "ecdsa", "hash2curve"], default-features = false }
#rand = "0.8"
hex = "0.4.3"
#methods = { path = "../counter_logic_circuit/methods" }
counter = { path = "../counter" }
rustler = "0.36.2"
serde = { version = "1.0.219", features = ["derive"] }
lazy_static = "1.5.0"
rand = "0.8.5"