# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    # branches: ["main"]
  pull_request:
    # branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    env:
      RISC0_DEV_MODE: true # use risc0 debug proving
      BUILD_NATIVE: true # compile the sdk, do not use precompiled

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-type: "strict"
          version-file: ".tool-versions"

      #----------------------------------------------------------------------------
      # Restore the cache.

      - name: restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-

      #----------------------------------------------------------------------------
      # Fetch and compile dependencies

      - name: install dependencies
        run: |
          mix deps.get

      - name: compile deps
        run: mix deps.compile

      #----------------------------------------------------------------------------
      # Lint

      - name: compile sdk
        run: mix compile --warnings-as-errors

      - name: check formatting
        run: mix format --check-formatted

      - name: check dialyzer
        run: mix dialyzer

      - name: check dependencies
        run: mix deps.unlock --check-unused

      - name: credo
        run: mix credo --strict

      #----------------------------------------------------------------------------
      # Run the tests

      - name: run tests
        run: mix test
