name: Rust CI
on:
  push:
    branches:
      - "*"
jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            target
          key: rust-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: rust-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: run rustfmt
        run: cargo fmt -- --check

      - name: run clippy
        run: cargo clippy -- -Dwarnings
